In [3]:
import sys
import numpy as np

print(f"Python {sys.version}")
print(f"Numpy {np.__version__}")

Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Numpy 1.14.3


In [4]:
# defining a scalar
x = 6
x

6

In [6]:
# defining a vector
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [7]:
print(f"Vector dimension {x.shape}")
print(f"Vector size {x.size}")

Vector dimension (3,)
Vector size 3


In [8]:
# defining a matrix
x = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
print(f"Matrix dimension {x.shape}")
print(f"Matrix size {x.size}")

Matrix dimension (3, 3)
Matrix size 9


In [14]:
# defining a matrix of a given dimention
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
print(f"Matrix dimension {x.shape}")
print(f"Matrix size {x.size}")

Matrix dimension (3, 3)
Matrix size 9


In [16]:
# defining a tensor
x = np.ones((3, 3, 3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [17]:
print(f"Tensor dimension {x.shape}")
print(f"Tensor size {x.size}")

Tensor dimension (3, 3, 3)
Tensor size 27


In [23]:
# indexing
A = np.ones((5, 5), dtype = np.int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
# indexing start at 0
A[0, 1] = 2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
A[:,0] = 3
A

array([[3, 2, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1]])

In [26]:
A[:,:] = 5
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [27]:
# for higher dimensions, simply add an index
A = np.ones((5, 5, 5), dtype= np.int)
A[:,0,0] = 6
A

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [31]:
# Matrix operations
A = np.matrix([[1, 2], [4, 5] ])
B = np.matrix([[2, 6], [2, 1] ])
# sum
C = A + B
C

matrix([[3, 8],
        [6, 6]])

In [29]:
# Subtrabtion
C = A - B
C

matrix([[-1, -4, -4],
        [ 2,  4,  1]])

In [32]:
# Multiplication
C = A * B
C

matrix([[ 6,  8],
        [18, 29]])

In [35]:
# The matri transpose
A = np.array(range(9))
A =  A.reshape((3, 3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])